In [1]:
import numpy as np
import numpy.linalg as npl

In [2]:
trainset_size = 100
num_feautures = 3
output_size = 2
x_arr = np.random.randn(num_feautures,trainset_size)*10
y_arr = np.random.randn(output_size,trainset_size)
print(x_arr.shape, y_arr.shape)

(3, 100) (2, 100)


In [3]:
P = npl.inv(x_arr @ x_arr.T )
theta = (P @  x_arr @ y_arr.T).T
print(theta, theta.shape)

y_hat = theta @ x_arr
print(y_hat.shape)

[[ 0.01739778  0.01533105 -0.00409941]
 [-0.00694881 -0.01238584  0.00220362]] (2, 3)
(2, 100)


In [4]:
x_arr_0 = x_arr[:,:trainset_size-1]
y_arr_0 = y_arr[:,:trainset_size-1]
print(x_arr_0.shape,y_arr_0.shape)
P_0 =  npl.inv(x_arr_0 @ x_arr_0.T)
theta_0 =  (P_0 @ x_arr_0 @ y_arr_0.T).T

print(theta_0, theta.shape)

theta_0 @ x_arr_0

(3, 99) (2, 99)
[[ 0.01731483  0.01572162 -0.00409804]
 [-0.00711817 -0.0115884   0.00220642]] (2, 3)


array([[ 3.16834548e-01,  1.00962753e-01, -3.40096213e-01,
         5.35497510e-02, -5.32114332e-03,  1.52387025e-01,
        -4.78999706e-01,  8.42221069e-02,  1.40854376e-01,
        -1.39303810e-01,  1.58066370e-01,  2.07912315e-01,
        -6.06720945e-02, -5.66964900e-02,  2.19668873e-01,
         3.85847208e-01, -1.31531310e-02, -3.97960131e-01,
        -8.91303843e-02, -8.27889491e-02,  1.74631562e-01,
        -4.63400903e-02,  3.57530386e-01,  1.32397384e-01,
        -2.27992514e-01,  4.41198925e-01,  1.80342291e-01,
        -1.88239391e-01,  1.77122224e-01, -5.30413748e-02,
         1.89483692e-01,  5.21014103e-02,  5.97461419e-02,
        -1.17087116e-01, -3.35003251e-01,  4.35139540e-02,
         8.79984144e-02, -5.25518089e-01, -1.70876403e-01,
        -1.21237674e-01,  1.29681952e-01, -2.07542819e-01,
        -3.39589366e-02,  3.56592841e-03, -1.55700212e-01,
         3.89650041e-01, -1.86414074e-01,  5.88141690e-01,
        -9.13226112e-02, -3.80168337e-01, -1.33645273e-0

In [5]:
# Choose next sample
print(x_arr.shape)
x_next = x_arr[:,trainset_size-1:trainset_size]
y_next = y_arr[:,trainset_size-1:trainset_size]

x_next.shape

(3, 100)


(3, 1)

In [6]:
P = npl.inv(x_arr @ x_arr.T)
theta_1 = theta_0 + (y_next - theta_0 @ x_next ) @ x_next.T @ P_0/ (1 + x_next.T @ P_0 @ x_next) 
print(theta_1)



[[ 0.01739778  0.01533105 -0.00409941]
 [-0.00694881 -0.01238584  0.00220362]]


In [7]:
print(theta_1)
print(theta)

[[ 0.01739778  0.01533105 -0.00409941]
 [-0.00694881 -0.01238584  0.00220362]]
[[ 0.01739778  0.01533105 -0.00409941]
 [-0.00694881 -0.01238584  0.00220362]]


## mu P x

In [16]:
print(x_arr.shape)
mu = x_arr.mean(axis=1,keepdims=True)
num_feautures - mu.T @ P @ mu

(3, 100)


array([[2.99989916]])

In [12]:
np.diag(x_arr.T @ npl.inv(P) @ x_arr)

array([ 2398453.02099769,  2312517.16032336,  9375396.38653269,
        1794501.88995796,  6553042.19752763,  1999611.6347128 ,
        3692685.27708703,  3357691.52539971,  1990996.03097671,
        1445083.90094342,  5902318.7821052 ,  6455770.86987024,
        1263427.69462772,  1365624.89497812,  2920771.78150313,
        2799878.49655485,  1707146.69528928,  4554118.77719647,
        5132691.98793826,  1396883.43449801, 10193020.42559849,
         376818.80801895,  2371619.43241196,  2369107.58505691,
        1480476.83919544,  3074131.55275023,  2001638.62821298,
        1003167.91967231,  2363325.05071031,  1243423.62119761,
        1452446.052125  ,  2682182.18257142,   407642.45952568,
        2527451.2184059 ,  2212873.9444232 ,  1300538.39624071,
        1772604.31287174,  7151997.31070658,  1856403.31771545,
        1576982.11434887,  3686460.11662417,  3714996.50109859,
         130572.30773708,  2754309.33702205,   965694.36501041,
        4313636.89908376,  4606512.46208

In [10]:
mu.shape

(3, 1)